### PR TITLE
Add support for reloading from YAML

### PR DESCRIPTION
**Pull request by postlund**
@rospogrigio Here's something to get going.

### CODE REVIEW

**Comment by rospogrigio** [comment]
Note to self: there are two situations to be handled:
1) the localtuya.reload service that reloads the entire localtuya YAML config
2) the Integration reload via the UI, that is supposed to reload only the selected integration. This is quite a new feature (introduced in 0.115.0), Info can be found here https://community.home-assistant.io/t/reload-integrations-indiviudally/220478/9

**Comment by rospogrigio** [comment]
Actually localtuya.reload seems to be already working in this PR.
Reloading a single integration does not, but I am not sure it is supposed to reload the YAML config, maybe it is just supposed to be restarted in case it misbehaves or seems unavailable. Currently, it does re-initializes but with the original YAML config data.

**Comment by postlund** [comment]
Ok, I got some problems when it did unloading or loading. Does it work as expected for you then?

The `reload` service basically reads the config from YAML, updates the corresponding config entry, then unloads and loads it again with new config. The "regular" one just unloads and loads again.

**Comment by rospogrigio** [comment]
I need to investigate more because it did fail once so I need to understand it better.
What do you mean by the "regular" one ? You mean the Integration reload from the UI?

**Comment by postlund** [comment]
That's good, test away! Yeah, via UI.

**Comment by rospogrigio** [comment]
This seems to work fine with me, I think we can merge it (unless it conflict with #62 , which I believe is more important).

**Comment by postlund** [comment]
If it works, then let's merge it. I can push an updated version. It shouldn't collide with #62.

**Comment by postlund** [comment]
@rospogrigio Review and merge when you are ready.

**Review by rospogrigio — APPROVED** [review]
The service localtuya.reload works (it reloads the YAML file from scratch, including what has changed).
The Reload for each Integration just restarts the integration, without re-reading YAML files, but probably it's how it's meant to be.

**Comment by rospogrigio** [comment]
Merging #61.

**Comment by postlund** [comment]
Yeah, that's how it's supposed to work.

**Pull request merged**
