### PR TITLE
Initial step to have continuous integration

### PR DESCRIPTION
**Pull request by postlund**
This commit introduces the use of tox, which currently only verifies
that code is formatted according to the black project. More checks will
come in upcoming PRs for codespell, pydocstyle, flake8 and mypy.

A GitHub actions is included that runs tox on new pull requests, so we
get automatic feedback and can block commits that fail any check.
Another (official) action that runs hassfest is included as well, to
make sure we are compatible with Home Assistant.

### CODE REVIEW

**Comment by postlund** [comment]
@rospogrigio Can you check if the top-most option under `Settings -> Actions` is selected?

**Comment by rospogrigio** [comment]
Yes it is.
Can you explain me how these tools work or send some documentation links so I can learn them?
Thx

**Comment by postlund** [comment]
Yeah, I will do a short write-up about it.

Ok, then it's probably because I'm creating a PR from a fork so it won't run the workflow due to security reasons. Maybe you can add me as a collaborator (`Settings -> Manage Access` I think)? Then I can push to this repo directly and create a PR from this repo instead, which will work better.

**Comment by rospogrigio** [comment]
OK, I guess you earned it 😄 , done! 😉

**Comment by postlund** [comment]
Awesome, thanks! 😎 I will close this PR and push to this repo instead!

**Pull request closed without merging**
