### PR TITLE
Add device discovery to config flow

### PR DESCRIPTION
**Pull request by postlund**
Devices are discovered during the first step and presented in a list. Let me know if it works!

### CODE REVIEW

**Comment by rospogrigio** [comment]
Looks cool! But:
1) I would simply not add the already configured devices to the list
2) some devices are missing :-o I must check if there was some connection problem though

**Comment by postlund** [comment]
1. Yeah, I was thinking about that as well. But decided to keep it simple. I can take a look and maybe add it, should be fairly simple.
2. That can be because of many reasons I guess (discovery is something that always will be tricky, especially when doing it on-demand). But... I'm not sure what the broadcast frequency of the devices is. I just hardcoded to five seconds to not delay the initial step for too long. I will try to figure out what the frequency is. If you abort the flow and try again a few times, are they found at some point?

**Comment by postlund** [comment]
Broadcast frequency is apparently five seconds (at least for my devices), so using that as an interval might not be a good idea. Perhaps increasing to six seconds is better.

**Comment by postlund** [comment]
I bumped timeout to six seconds and now filter devices that have already been added. Give it a new go and let me know if it works!

**Comment by rospogrigio** [comment]
Works perfectly. One last thing I'd add is not letting the user edit the parameters detected by the discovery, since they are clearly not meant to be changed (in particular, devID and protocol). Don't know whether it's feasible/easy to do though.

**Comment by postlund** [comment]
I don't think it's possible to lock certain fields in a flow from editing. They would have to be omitted instead. That is of course possible, but then I would like to have the values of these fields included in the step description. Unfortunately it's not possible to have more than one description per step (here we would need one for the normal flow and additional ones for the locked fields due to translation reasons), which means we have to add an additional step in the flow solely for this purpose. I would say the benefits does not outweigh the cost. See the discovery step more of a "pre-filler" than anything else I would say.

**Comment by rospogrigio** [comment]
OK I agree the effort is much less than the advantage then. I'll merge this very soon, I am trying to accomplish the "one-device-only" thing and I think I'm pretty close, I'll come with a PR for your evaluation tomorrow I guess. 😉

**Comment by postlund** [comment]
@rospogrigio You can probably hook in to #30 with "one-device-only" quite easily.

**Pull request merged**
