### PR TITLE
Fix broken status for 0d devices

### PR DESCRIPTION
**Pull request by postlund**

### CODE REVIEW

**Comment by rospogrigio** [comment]
Still not working. Logs:
```
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Started heartbeat loop
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command heartbeat (device type: type_0a)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{}'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number -100
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Got heartbeat response
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command status (device type: type_0a)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{"gwId":"bf89d2c3ba66cb83288njv","devId":"bf89d2c3ba66cb83288njv"}'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number 1
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b''
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {}
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Dispatching sequence number 1
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b'j\x16-\x11~\xdbs-B\xa8\x9er\xbc\xaf\x0c\xb5i\xa6M\xc3*\xfa\x87\xfa"\xedn\xaf\xc85\x05\x92'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] switching to dev_type type_0d
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Re-send status due to device type change (type_0a -> type_0d)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command status (device type: type_0d)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602750368","dps":{"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null}}'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number 2
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Got status update
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Dispatching sequence number 2
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b''
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {}
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command status (device type: type_0d)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602750368","dps":{"1":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null}}'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number 3
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Got status update
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Dispatching sequence number 3
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b''
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {}
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command status (device type: type_0d)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602750368","dps":{"1":null,"21":null,"22":null,"23":null,"24":null,"25":null,"26":null,"27":null,"28":null,"29":null,"30":null}}'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number 4
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Got status update
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Dispatching sequence number 4
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b''
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {}
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command status (device type: type_0d)
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602750368","dps":{"1":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null,"107":null,"108":null,"109":null,"110":null}}'
2020-10-15 10:26:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number 5
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Got status update
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Dispatching sequence number 5
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b''
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {}
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] detected dps: {}
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Closing connection
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Connection lost: None
2020-10-15 10:26:09 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Closing connection

```

**Comment by postlund** [comment]
Really strange. I pushed an update that logs the messages, can you try that?

**Comment by rospogrigio** [comment]
Since you removed the self.dps_to_request, I could not authenticate with the device, and I got this error:

```
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Re-send status due to device type change (type_0a -> type_0d)
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Sending command status (device type: type_0d)
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602751686"}'
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Send message: TuyaMessage(seqno=2, cmd=13, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x86$G\xc7\xb8q\x9ezs\xd1#\x18\xd6I\xe2\xaf\x9e\xa4%\xd6\x0f\xb4\xf1\xd6AZ\x9dU)7\x88zt\xd5TD\x06w-\xaf\x0e\xf1J\\y\xd4\n(Z\xe1!\xcfg\x99#\xce\t\xf3\xd9Ff\xdd\xd7"\x1af\x8e"\t\xfae:\xb4C\xed\xed\xf0^\xea\x88R*T=8F\xa0\xde\xcb\xfd\xc2N\x96Y/\x0b', crc=0)
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Waiting for sequence number 2
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Message: TuyaMessage(seqno=2, cmd=13, retcode=1, payload=b'J>\xb9&\xb9\x1cV\x9c\xfe+)\xe8\xdanT\x9a\xa7"=\xae(C\x80\xc0S\xe3!\x08X\xfcM\x0f', crc=448349353)
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Dispatching sequence number 2
2020-10-15 10:48:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decode payload: b'J>\xb9&\xb9\x1cV\x9c\xfe+)\xe8\xdanT\x9a\xa7"=\xae(C\x80\xc0S\xe3!\x08X\xfcM\x0f'
2020-10-15 10:48:06 WARNING (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Failed to get status: The length of the provided data is not a multiple of the block length.

```
So I restored that code, and here is the log I got:

```
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Waiting for sequence number -100
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Sending command status (device type: type_0a)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Paylod: b'{"gwId":"bf89d2c3ba66cb83288njv","devId":"bf89d2c3ba66cb83288njv"}'
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Send message: TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\xd5Od\x11\x08\x87S2\xc2\x0b\xb5\xfevc\r;Z\xe1!\xcfg\x99#\xce\t\xf3\xd9Ff\xdd\xd7"\xd8\xcaD\xaf\x84\xfb\xde\xfa\x94^E\xa6\xb6w\xe6X\x9e\xa4%\xd6\x0f\xb4\xf1\xd6AZ\x9dU)7\x88zR*T=8F\xa0\xde\xcb\xfd\xc2N\x96Y/\x0b', crc=0)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Waiting for sequence number 1
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Message: TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Got heartbeat response
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Message: TuyaMessage(seqno=1, cmd=10, retcode=1, payload=b'j\x16-\x11~\xdbs-B\xa8\x9er\xbc\xaf\x0c\xb5i\xa6M\xc3*\xfa\x87\xfa"\xedn\xaf\xc85\x05\x92', crc=863068496)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Dispatching sequence number 1
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decode payload: b''
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decrypted payload: {}
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decode payload: b'j\x16-\x11~\xdbs-B\xa8\x9er\xbc\xaf\x0c\xb5i\xa6M\xc3*\xfa\x87\xfa"\xedn\xaf\xc85\x05\x92'
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] switching to dev_type type_0d
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Re-send status due to device type change (type_0a -> type_0d)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Sending command status (device type: type_0d)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602751799","dps":{"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null}}'
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Send message: TuyaMessage(seqno=2, cmd=13, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x86$G\xc7\xb8q\x9ezs\xd1#\x18\xd6I\xe2\xaf\x9e\xa4%\xd6\x0f\xb4\xf1\xd6AZ\x9dU)7\x88zt\xd5TD\x06w-\xaf\x0e\xf1J\\y\xd4\n(Z\xe1!\xcfg\x99#\xce\t\xf3\xd9Ff\xdd\xd7"s\xa9\xa9\xe6Z\x1a\xc0\x92\xae\xdf\\)g\xad\xc0@\x10\xd5\xffi\x00\xb3\x87\x0f`\xa4\x1a\xa6\xa1(\xe9C\x01iT\xfbz\x00\x9c\x95\x96\x1e\x99*\xcbx\xb0k\xf0\xb91\xe5\xc4\xa0\xd2q\xda0/\xab\x9b\xa4J=\xc3\xefs\xd3\x9d\xdf \x90\xfb\x12\x8d\xf8\x1c\xdak\xab\x8a\xc5\xd7\xe5\xb8$Oz\xaf\xdfM\xf6\xdd\xbf,OD\x01[\x8f\xb4\x08\xe3\xe6\x15\x88\xc3m\xb7\xca-<\x06\x1c\x0f\xdco\xee\x97\xca\x1f]\x11\x10\xadaiF', crc=0)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Waiting for sequence number 2
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Message: TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x8e\x13\x00\x00\x00\x01\xb7D\xcf2_~wd\xa1\x7f_\x97\xb1\xf5\xa3\x94\x1f[?O\x87 N\xda\x08\xa3\xb4\xa2m\xcc\x1c\x07\x91\xf4LK6\x06Y(($\xed\xc3\xc1c1\x8d', crc=2784905551)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Got status update
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Message: TuyaMessage(seqno=2, cmd=13, retcode=0, payload=b'', crc=2380353348)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Dispatching sequence number 2
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decode payload: b''
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decrypted payload: {}
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Sending command status (device type: type_0d)
2020-10-15 10:49:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602751799","dps":{"1":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null}}'
[...]

```

**Comment by rospogrigio** [comment]
FYI, here is the handshake of the same device if configured with YAML:

```
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b''
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {}
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Message: TuyaMessage(seqno=1, cmd=10, retcode=1, payload=b'j\x16-\x11~\xdbs-B\xa8\x9er\xbc\xaf\x0c\xb5i\xa6M\xc3*\xfa\x87\xfa"\xedn\xaf\xc85\x05\x92', crc=863068496)
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Dispatching sequence number 1
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b'j\x16-\x11~\xdbs-B\xa8\x9er\xbc\xaf\x0c\xb5i\xa6M\xc3*\xfa\x87\xfa"\xedn\xaf\xc85\x05\x92'
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] switching to dev_type type_0d
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Re-send status due to device type change (type_0a -> type_0d)
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Sending command status (device type: type_0d)
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Paylod: b'{"devId":"bf89d2c3ba66cb83288njv","uid":"bf89d2c3ba66cb83288njv","t":"1602752298","dps":{"1":null}}'
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Send message: TuyaMessage(seqno=2, cmd=13, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x86$G\xc7\xb8q\x9ezs\xd1#\x18\xd6I\xe2\xaf\x9e\xa4%\xd6\x0f\xb4\xf1\xd6AZ\x9dU)7\x88zt\xd5TD\x06w-\xaf\x0e\xf1J\\y\xd4\n(Z\xe1!\xcfg\x99#\xce\t\xf3\xd9Ff\xdd\xd7"\x0b\x1a\'/T\x9azf\xe0\xca\xaa\'\x88\x8enV\x10\xd5\xffi\x00\xb3\x87\x0f`\xa4\x1a\xa6\xa1(\xe9C\xe5p\xb0\x0f\xa2?1\x8f\xfef\x9f\xd6\xcd\xc2\xf9q', crc=0)
2020-10-15 10:58:18 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Waiting for sequence number 2
2020-10-15 10:58:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Message: TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00\x8e\x17\x00\x00\x00\x01\xb7D\xcf2_~wd\xa1\x7f_\x97\xb1\xf5\xa3\x94K\x9a\xca\x12wI"F\n\xde\xb0Q\x9e\xd434\xc9v\x0b\x85\x98e\x9bA\x17\xd5\x91\x88\x1c\xa7{`', crc=438253190)
2020-10-15 10:58:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Got status update
2020-10-15 10:58:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decode payload: b'3.3\x00\x00\x00\x00\x00\x00\x8e\x17\x00\x00\x00\x01\xb7D\xcf2_~wd\xa1\x7f_\x97\xb1\xf5\xa3\x94K\x9a\xca\x12wI"F\n\xde\xb0Q\x9e\xd434\xc9v\x0b\x85\x98e\x9bA\x17\xd5\x91\x88\x1c\xa7{`'
2020-10-15 10:58:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89....8njv] Decrypted payload: {"dps":{"1":"stop"},"t":1602752298}
```

Let me know if you need the localKey for decrypting, in case...

**Comment by postlund** [comment]
Ok, right, we need to keep that special case. We can skip this PR altogether now. But, based on this, my theory is that the 0xd command changes something that triggers a status update. So the fact that we get datapoints here is just a side-effect of that (actual response to 0x0D is empty). That is why it doesn't work with my dispatcher and it is also hard to solve in a good way. I can probably create a work-around for this though.

**Comment by rospogrigio** [comment]
I don't seem to have understood anything of what you just wrote 😆

**Comment by postlund** [comment]
In case of 0a devices, we send a request with sequence number X and get a response with all DPSes to sequence number X. For 0d devices we do the same, but the response we get is empty and a status update is pushed from the device (just like we handle push updates now with asyncio), containing the values of the DPSes we requested. So we need to map these together and I have an idea.

**Comment by rospogrigio** [comment]
OK now I see. I had thought it had to do with the "double read" that I needed to to with old pytuya, but I added some logs to tuyadebug and these devices never request a double read.
Will wait for your fix then...

**Comment by rospogrigio** [comment]
Mmmm there is something unclear in what you just wrote. Why does it work when we request a status normally (on a YAML-configured device)? It's actually the same status() request, with dps_to_request properly filled... why does it work in that case? I'm confused.

**Comment by postlund** [comment]
@rospogrigio I can actually explain that. My changes in this PR are not needed as we always override the DPS we request with `dps_to_request` for 0d devices. When we configure with YAML (or have a properly setup config entry), we will always populate that list with the datapoints used by the entities during set up up a device. With the move to asyncio/persistent connection, we only do *one* manual status call and then rely on push updates. Since we have our main problem, that status call will "fail" and just return an empty dict. So, we store an empty dict. But since we made the status request with all the datapoints we need, there will also be an instant push update from the device with the values of these datapoints. Since we handle these push updates here, we recover even if the status call doesn't work as expected.

**Comment by postlund** [comment]
Now I'm starting to re-think how to make my changes. I should probably just cache all datapoints in pytuya instead. Will make things a lot easier.

**Comment by postlund** [comment]
@rospogrigio Pushed a quick prototype, please let me know if it works.

**Comment by rospogrigio** [comment]
Well, did not follow you 100% but it actually works, well done!! 💪  You probably want to change some debug lines where you used print, right? Are you interested in watching some logs?

**Comment by postlund** [comment]
Yeah, it was meant as a prototype. Will clean it up later.

**Comment by postlund** [comment]
@rospogrigio Cleaned up now. Give it a try again to make sure it works, then merge when you feel like it!

**Review by rospogrigio — APPROVED** [review]

**Comment by rospogrigio** [comment]
Works perfect now. Merging #84.

**Pull request merged**
