### PR TITLE
Remove pull_request_target from ci workflow

### PR DESCRIPTION
**Pull request by postlund**

### CODE REVIEW

**Comment by rospogrigio** [comment]
> Just created a new PR ([rospogrigio#42](https://github.com/rospogrigio/localtuya-homeassistant/pull/42)), anything strange there?

Nope, this PR works fine here.

**Comment by rospogrigio** [comment]
Ehi, I see the automatic Checks... how does this work? How can we run this for #40?

**Comment by postlund** [comment]
The checks are run automatically on all pull requests and all updates to them, e.g. if you push new commits. Old pull requests might be in a limbo though. You can try pushing something to #40 to see if it gets picked up.

The `CI` workflow is triggers by this line and you can also see what is done for that workflow:

https://github.com/rospogrigio/localtuya-homeassistant/blob/ec7652b19382c4bc0d43843c7dedb5bcc31c17a6/.github/workflows/ci.yaml#L3

One thing you can do now is to go to `Settings -> Branches` and press Edit next to the `master` branch. Here you can tick *Require status checks to pass before merging*, *Require branches to be up to date before merging*, all the status checks in the list and *Require linear history*. This will prevent merged if checks fail. It could be interesting to use *Require pull request reviews before merging* as that requires at least one of us to look and press approve at a PR before merging. It can be kinda good to prevent hasty merging of stuff.

**Comment by rospogrigio** [comment]
Done 👍

**Comment by postlund** [comment]
Great! 👍

**Pull request merged**
