### PR TITLE
Extract common code

### PR DESCRIPTION
**Pull request by postlund**
The `LocalTuyaEntity` contains common entity code and is also based on a config entry, which will allow us to adjust to changes options automatically. Only implemented for switch here, will do the other platforms separately. Please have a look at this @rospogrigio, it will save us a lot of code.

### CODE REVIEW

**Comment by rospogrigio** [comment]
Looks cool, I already solved the conflicts. Shall I merge or do you want to extend this to the other platforms here?

**Comment by postlund** [comment]
Have a look at the comment I wrote about name in device_info. I can push a fixed version commit which applies cleanly, so you don't have to worry about it 😊 But after that we can merge, I'll deal with the other platforms soon. Would be good if you could look at 14 as well.

**Comment by rospogrigio** [comment]
Just tried this... something weird is going on with my switches. They always appear ON, and if I switch them OFF they get back to ON after like 1 second... ?!?

**Comment by postlund** [comment]
Found an error in the attributes, will fix that later. Seems I have the update error also, will need to look at that.

**Comment by postlund** [comment]
@rospogrigio Should be fixed now!

**Comment by rospogrigio** [comment]
OK, merging!

**Pull request merged**
