### PR TITLE
Get status once per device instead of per platform

### PR DESCRIPTION
**Pull request by postlund**
This is the one that needs some serious testing.

### CODE REVIEW

**Comment by rospogrigio** [comment]
I am getting (sorry, too late to debug for me, going to bed...):
`2020-09-26 22:53:28 ERROR (MainThread) [homeassistant.components.cover] Error while setting up localtuya platform for cover
Traceback (most recent call last):
  File "/root/home-assistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/root/home-assistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/root/home-assistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/root/home-assistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 522, in add_to_platform_finish
    self.async_write_ha_state()
  File "/root/home-assistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/root/home-assistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 317, in _async_write_ha_state
    if not self.available:
  File "/root/etc2/custom_components/localtuya/cover.py", line 84, in available
    return self._available
AttributeError: 'LocaltuyaCover' object has no attribute '_available'
`

**Comment by rospogrigio** [comment]
And still I get occasional of these errors:
`Failed to receive data from 192.168.1.26. Raising Exception.
Failed to update status of device [192.168.1.26]`

**Comment by postlund** [comment]
Some relic override of `available`. I removed it and pushed again, so you can try again now.

Maybe no connection problems was a lucky shot for me.

**Comment by rospogrigio** [comment]
I've done some research, and somebody says that this behavior might be caused by opening and closing the socket for each request: https://github.com/codetheweb/tuyapi/issues/84 .
So I'd merge this PR, and implement the persistent socket immediately to check if it solves. 
Do you want me to do it or do you want to do it yourself?
Let me know!

**Review by rospogrigio — APPROVED** [review]

**Comment by rospogrigio** [comment]
PR #51 merged into master.

**Comment by rospogrigio** [comment]
> So I'd merge this PR, and implement the persistent socket immediately to check if it solves.
> Do you want me to do it or do you want to do it yourself?

I've sketched something, and it does seem to keep the connection more robustly...

**Comment by postlund** [comment]
I agree, we should definitely move towards a persistent connection. I think I included that in my "future" issue (#15). Also, clean up and convert to asyncio. If you have something up and running worth looking at, open a PR and we can look at it together 😊

**Comment by rospogrigio** [comment]
OK @postlund , but before we move to the persistent connection, I have something else to submit to your attention. In detail:
1) there is a serious bug in this PR. What I am experiencing is that if I toggle a switch (or a cover command), in the web interface the switch bounces back to its original status, until the status of the device is polled and then the switch status is updated correctly. I tested that in the previous commit is not present. Please confirm that you are experencing the same issue.
2) I created a new PR (see #55), that would use the response of the set_dps() call to update the TuyaDevice status, that requests your review and support, please let me know what you think

After we've fixed these 2, we can move on to persistent connection.

**Comment by rospogrigio** [comment]
Jeeez, I've struggled really hard to comply to the lint and pydocstyle remarks, don't you think some rules are a bit too strict?
Also, how can I run these tools locally so I can pre-test before pushing garbage?
Thank you

**Comment by postlund** [comment]
As long as you don't override 88 characters in comments, running `black .` should sort everything out for you. Most other things are common sense or PEP8. Anything in particular you feel are to strict? I added a short text to the wiki, maybe we can let that grow over time.

**Comment by rospogrigio** [comment]
Well, things like "Words must be imperative, not in 3rd person", or "missing trailing period"... I found them a bit too much 😆

**Comment by rospogrigio** [comment]
PS, what about the bug I reported?

**Comment by postlund** [comment]
Yeah, ok, some of the pydoc stuff can be a bit much.... 😉

Yeah, you are right regarding the bug. Since we now have an external loop that updates everything, service calls can't trigger additional state changes. The trivial way would be to somehow trigger an update after changing a DP. This has a small cost of course, since we have to fetch all DPS again, but this only happens when changing a DP which is very seldom when amortized over time (so a drip in the ocean). But, since you have already made a more optimized version we can probably go that route as well. We just need to send out the updated status (full cache) to all entities. I can add some comments in your other PR.

**Pull request merged**
