### PR TITLE
Add generic binary_sensor platform

### PR DESCRIPTION
**Pull request by postlund**
Allows creation of a `binary_sensor` based on arbitrary DP. Strings can be provided for "on" and "off" and are case-insensitive.

### CODE REVIEW

**Comment by postlund** [comment]
Trying to get this in before refactoring to avoid conflicts later.

**Comment by postlund** [comment]
@rospogrigio This should be rebased and ready now. Would be nice to get it in before I'm ripping out a lot of code for the schema changes.

**Review by rospogrigio — APPROVED** [review]
OK

**Comment by rospogrigio** [comment]
;erging #37 to master

**Pull request merged**
