### PR TITLE
Revert some friendly_name changes

### PR DESCRIPTION
**Pull request by postlund**

### CODE REVIEW

**Comment by postlund** [comment]
Maybe we can get going with this so I can fix my other commit?

**Comment by rospogrigio** [comment]
Mmm @postlund , this PR does not convince me.
Maybe we are focusing a bit too much on things that can actually be renamed at owner's taste using the UI, anyway:
1) for the Integration name, you use the notation "**_deviceID_** (import from configuration.yaml)", while I frankly prefer my "device_friendlyName (YAML)", which is more readable and more clear. You'll probably be concerned by the risk of having duplicates? I see that some integrations use the IP address here... still I'd prefer the friendlyName, and let the user set what they want; in the end I guess it's just a matter of taste here, since it can be renamed at will.
2) for the `name` within the `device_info` block instead, you have basically made the same thing I did, apart for what happens in switches. Your implementation gives the Device the same name of the last subswitch Entity, instead of the Device's friendly name. Please note that I was passing `config_entry.data[CONF_FRIENDLY_NAME])` (line 66) which is the device's friendly_name, while you end up giving it the friendly name of each Entity, so the last one prevails in the end
In the end, I'd leave things as they are in master branch if you don't mind, unless you want to discuss this further.

**Comment by postlund** [comment]
@rospogrigio Ok, ok, ok, you can have your wish regarding `friendly_nane` but you will have to remove `name` in that case. We should not have both.

In `device_info` I pass `self.name` as `name`, which in turn returns `self._name` within the entity (e.g. a switch, cover, ...). If we look into the constructor for let's say the `switch`:

```python
    def __init__(
        self,
        device,
        friendly_name,
        switchid,
        attr_current,
        attr_consumption,
        attr_voltage,
    ):
        """Initialize the Tuya switch."""
        self._device = device
        self._name = friendly_name
        self._available = False
        self._switch_id = switchid
        self._attr_current = attr_current
        self._attr_consumption = attr_consumption
        self._attr_voltage = attr_voltage
        self._status = None
        self._state = None
        print(
            "Initialized tuya switch [{}] with switch status [{}] and state [{}]".format(
                self._name, self._status, self._state
            )
        )
```
`self._name` is assigned `friendly_name` here, so it's exactly the same thing you did but we don't need to pass the variable around in unneeded places.

**Comment by postlund** [comment]
Right, now I see the "issue" with (2) here (still too early in the morning). Ok, this can remain for now until I figure out how devices should be set up properly. It feels so redundant and wrong to return the exact same thing everywhere...

**Comment by rospogrigio** [comment]
> @rospogrigio Ok, ok, ok, you can have your wish regarding `friendly_nane` but you will have to remove `name` in that case. We should not have both.

Yes, I do agree we should remove the `name` from everywhere because it just creates confusion and it's pretty useless (since I cannot use it to set the entity_id, damn!!! 😆 ). I will do it soon.

> `self._name` is assigned `friendly_name` here, so it's exactly the same thing you did but we don't need to pass the variable around in unneeded places.
> Right, now I see the "issue" with (2) here (still too early in the morning). Ok, this can remain for now until I figure out how devices should be set up properly. It feels so redundant and wrong to return the exact same thing everywhere...

This is true for all platforms except switches, where you have different friendly_names for the main device and for the subswitches, but I kept the same structure for all devices for uniformity. I actually don't know if there may be multi-covers with more than 1 cover entity within the same device (would need to change the YAML structure too in this case, obviously).

**Comment by postlund** [comment]
> Yes, I do agree we should remove the `name` from everywhere because it just creates confusion and it's pretty useless (since I cannot use it to set the entity_id, damn!!! 😆 ). I will do it soon.

Yeah, at least like we have it now. It would of course be possible to add it back everywhere and actually use. But I still suggest we don't for simplicity.
places.

> This is true for all platforms except switches, where you have different friendly_names for the main device and for the subswitches, but I kept the same structure for all devices for uniformity. I actually don't know if there may be multi-covers with more than 1 cover entity within the same device (would need to change the YAML structure too in this case, obviously).

It is good to be consistent, that is mainly what I'm trying to do with the config entries and config flows. I also opened #22 for this reason. The changes you made assumed that the entities were set up from YAML and the it's correct (aside from subswitches). But when you set up from a config flow you could add 150 switches, 45 covers, 60 fans, 92 lights and possibly any other numbers of platform types in the future **to the same device**. We don't put any restrictions on that in the implementation now (what *actual* hardware exists in reality is another matter).

The whole idea of how devices work here is bonkers to me. It makes sense that a device is created automatically if you provide `device_info` for a single entity. It makes things easy. But that you have to provide the *exact same* information in `device_info` for all entities that happens to belong to the same hardware is just plain redundant. And what happens when you change `friendly_name` for the device but still have the old name cached in the entities, because it was passed to the constructor? It makes a lot more sense to me to define a device in one place and then refer to that device via an identifier rather than making sure entities return the exact same `device_info`.

A lot of this will be cleaned up with LocalTuyaEntity since information is taken from the config entry instead.

**Comment by rospogrigio** [comment]
> And what happens when you change `friendly_name` for the device but still have the old name cached in the entities, because it was passed to the constructor?

My understanding is that, while the "identifiers" part remains the same (as will always be, since we'll be using the deviceId here) the entities will always remain related to the same device. Regarding the friendly_name, this PR has shown that every entity being set up may change the device_info at will, and the last one being set up will have the last word. I agree that it looks a bit cumbersome, but still.

**Comment by postlund** [comment]
> My understanding is that, while the "identifiers" part remains the same (as will always be, since we'll be using the deviceId here) the entities will always remain related to the same device. Regarding the friendly_name, this PR has shown that every entity being set up may change the device_info at will, and the last one being set up will have the last word. I agree that it looks a bit cumbersome, but still.

Yeah, it makes sense that the identifiers are used for mapping to the device registry. But if this is just a race to who happens to be the "last one" returning something related to that an identifier in `device_into`, then we are doing something wrong. The behavior should be deterministic. Otherwise it makes no sense.

**Comment by rospogrigio** [comment]
I had a look at daikin component, and I think we should just copy what is done there.
An Appliance is created within __init__.py in `async_setup`, which is the equivalent of our TuyaDevice. It is then passed as api parameter to the various platforms to create entities. Each platform in the `device_info `method returns the device_info of the Appliance.
Looks very clean and quite correct. Will try to refactor this way, it'll be a long job but will make things everything right. Agree?

**Comment by postlund** [comment]
I still don't think that is correct. We should create a device when setting up the config entry, then just refer to that device via some identifier in the entities to map entities to the device. I looked at esphome which uses `connections` in the entities to match its parent device. This looks way more correct as we only want to link the entities, not create new devices (I guess). But it depends on MAC for the connection, which we don't have. The other types are zwave and zigbee so I'm not sure if this is for us.

When looking at the Hue light example (https://developers.home-assistant.io/docs/device_registry_index/) they) they use the unique identifier of *each individual light entity*, not the bridge to which they are connected. They also use the name of each individual light, since they use `self.name` like I did.

There are discrepancies in various integrations because they might have done something in the past, which then have changed. So it's not always possible to look at an integration and assume it's right anymore, I've been bitten by that before. What's being done might work but still not be the correct way of doing things.

**Comment by postlund** [comment]
And please, don't make big refactoring jobs until we have merged #18. It will just create merge hell later, we need to keep track of our dependencies so we don't create unnecessary merge conflicts. Feel free to merge #18 if you like.

**Comment by rospogrigio** [comment]
OK but I see that #18 has conflicts, will you fix them or do you want me to do it?

**Comment by postlund** [comment]
Just fixed the conflicts 👍

**Comment by rospogrigio** [comment]
> When looking at the Hue light example (https://developers.home-assistant.io/docs/device_registry_index/) they) they use the unique identifier of _each individual light entity_, not the bridge to which they are connected. They also use the name of each individual light, since they use `self.name` like I did.

I don't think Hue lights are similar to our devices. Being just bulbs, it is very plausible that they just provide 1 entity, so there is a "1 device-1 entity" relationship, while we have "1 device-many entities" relationship. 
 
> There are discrepancies in various integrations because they might have done something in the past, which then have changed. So it's not always possible to look at an integration and assume it's right anymore, I've been bitten by that before. What's being done might work but still not be the correct way of doing things.

OK let's study a bit more before starting the coding, will have a look at esphome as well.

**Comment by rospogrigio** [comment]
Had a look at esphome, and it looks to me that the approach is quite similar to the Daikin component, even if a more complex syntax is being used. The device is created in the __init__.py, and all entities inherit from EsphomeEntity (like we are doing in #18 ), and they all return the same device_info data, related to the main device.
Also, I believe that the whole DeviceRegistry thingy has no practical utility, other than regrouping nicely the Entities in the Configuration-Devices frontend page... I mean, even if we don't create a Device Registry record, we would still be able to make things work nicely. Do you agree?

**Comment by rospogrigio** [comment]
> Also, I believe that the whole DeviceRegistry thingy has no practical utility, other than regrouping nicely the Entities in the Configuration-Devices frontend page... 

Actually, it appears that defining a Device in the DeviceRegistry is useful to define Scenes and Automations from the Device frontend. It also appears that there is no difference between using the connections and the identifiers tags, in the end they are just different ways to have the entities regrouped under the same Device. Unless there's something I am missing.

**Comment by postlund** [comment]
Yes, device automations is one of the main benefits we get here. By being compliant with the device registry we will potentially also get new features for free (when added). We should conform to the concept, that's what's important.

Anyway, I spoke to Robban who created the device registry in the first place and I feel that I understand the concept a bit better now. The information in `device_info` is read when an entity is added to Home Assistant. HA will then look into the device registry in order to find the device it refers to (using `identifiers` and `connections`), automatically creating a new device if one does not exist or populating an existing device with the new information. By doing this, different integrations can help out populating the database and also find inter-relationships. Let's take an example. You run a device tracker that discovers devices on the network, which picks up your device. It know very little about it, just things like MAC address and IP address but populates the device registry with the device, adding MAC as as a "connection". Another integration that actually knows what the device is (like localtuya *knows* what a Tuya device is) also populated the device registry with the same device, but fills in the blanks (like model and name), adding MAC address to "connections" as well. This will merge more data into the device registry entry, giving the device tracker more information as well about the device since they can share data. Pretty good idea.

So, this can in theory be done in several ways:
1. We know all information about the device already from the config entry, so we could set up the device once and then refer to it only via "identifiers" in our entities to create the connection between device and entity.
2. Only one entity needs to provide the complete information (since that would populate the device registry completely), so it would work equally good to return everything in the first entity we add and then just "connections" in the rest. Not very practical to implement, but would work.
3. Look at each entity individually and let them tell the device registry about its view, I.e. return all information it knows about its parent device.

Due to re-use and all that (already covered) I'm more in the 1. camp, but now after shifting view on things I can kinda accept 3. At least now when I understand *why* it is done this way. Since we already have 3 implemented, all is good. I think we can close this and focus on #23 which should be good for now. I noticed that I missed the translation, I will update that.

**Comment by postlund** [comment]
And oh, we need to remove the "model" attribute as that doesn't make sense. We only have one device and that device can only have one model name. We will get the "last-entity-determines-the-value"-situation, which would just be defined by the order platforms are added. In realty this field should be populated by the manufacturers model, but we don't know that so we can leave it out.

**Pull request closed without merging**
