### PR TITLE
Fix fan platform after merge

### PR DESCRIPTION
**Pull request by postlund**
@rospogrigio I think you managed to miss most of the stuff in the fan PR when fixing the conflict. I re-applied that PR and verified by adding both a single and double gang socket with success. So this should be fine.

### CODE REVIEW

**Comment by rospogrigio** [comment]
Yes, looks like I lost part of the code... this PR does not work for me anyway, it does not go beyond
`2020-09-13 19:24:43 INFO (MainThread) [homeassistant.components.switch] Setting up switch.localtuya`
I'll debug further since it's the same behavior I get in #7.
Keep you posted.

**Comment by postlund** [comment]
Are there any other errors? Did you check if the config entry has been created under Integrations?

**Comment by rospogrigio** [comment]
No, no errors, no entities created, no config entry, nothing.

**Comment by postlund** [comment]
Look for `localtuya` in core.config_entries, especially if you have entities without the `platform` attribute. Probably the case of if used the "switch PR".

**Comment by rospogrigio** [comment]
Don't understand what you said... Can you explain? I am trying to keep it
simple, I have only one smart switch configured via yaml and it does not
appear.


Il Dom 13 Set 2020, 19:36 Pierre Ståhl <notifications@github.com> ha
scritto:

**Comment by postlund** [comment]
A config entry contains a list of all configured entities, e.g. switches, lights and fan. When a config entry is loaded, that list is iterated and forwarded to each platform. So the switch platform for instance will receive the config entry (via `async_setup_entry`), iterate through the list of entities and set up all entities with `platform` set to `switch`. Here is an example with my switches:

```json

{
    "version": 1,
    "key": "core.config_entries",
    "data": {
        "entries": [
            {
                "entry_id": "208c55aef5e311ea8cb6d1f631c3b4f1",
                "version": 1,
                "domain": "localtuya",
                "title": "Single",
                "data": {
                    "device_id": "xxx",
                    "entities": [
                        {
                            "id": "1",
                            "friendly_name": "single",
                            "current": "37",
                            "current_consumption": "19",
                            "voltage": "20",
                            "platform": "switch"
                        }
                    ],
                    "name": "Single",
                    "host": "10.0.10.105",
                    "local_key": "xxx",
                    "protocol_version": "3.3"
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": "xxx"
            },
            {
                "entry_id": "6681f638f5e311eab089c9910c3e7162",
                "version": 1,
                "domain": "localtuya",
                "title": "dual",
                "data": {
                    "protocol_version": "3.3",
                    "name": "dual",
                    "host": "10.0.10.100",
                    "device_id": "xxx",
                    "local_key": "xxx",
                    "entities": [
                        {
                            "friendly_name": "first",
                            "id": "1",
                            "current": "18",
                            "current_consumption": "19",
                            "voltage": "20",
                            "platform": "switch"
                        },
                        {
                            "friendly_name": "second",
                            "id": "2",
                            "current": "18",
                            "current_consumption": "19",
                            "voltage": "20",
                            "platform": "switch"
                        }
                    ]
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": "xxx"
            }
        ]
    }
}
```
As you can see, each entity under `entities` has `platform` set to `switch`. If this is missing (which might be the case), no entity will be set up at all since the platform is missing. Could be worth verifying. You should at least start by verifying if you have an entry or not in`.storage/core.config_entries`.

**Comment by rospogrigio** [comment]
Wow, this is precious info. Well, after some time of moving back and forward from #6 to #7, here is what happens:
1) I only have 1 double switch configured via yaml
2) in #6, it correctly creates an Integration (with the id, "import from configuration.yaml"), and everything works. If I delete the integration, it is correctly restored after a restart. Logging messages show that async_setup_entry is correctly invoked
3) in #7, it does not create the Integration, and I don't see the switch in core.config_entries. As a consequence, the entity is present if the Integration is there, but if I delete it, it is not restored after a restart. Logging messages show that async_setup_entry is NOT invoked so I guess there is some syntax error somewhere
Will try to figure it out, let me know if you have a guess on where the problem can be.

**Comment by postlund** [comment]
With #7 applied, you should debug the import step in `config_flow.py` to see what happens.

**Comment by rospogrigio** [comment]
Actually, I believe that the error is in:
`def prepare_setup_entities(config_entry, platform, device_class):`
since neither switch nor light are sending the 3rd parameter, which I believe should be removed in view of the refactored pytuya library.
Will try to fix it and see if it all starts working...

**Comment by postlund** [comment]
The code that is currently on `master` passes that parameter (as it should)? So I'm not sure what you are running if it's not in your code. But you are right, with your refactor that has to be changed since no platform specific device types needs to be used anymore.

**Comment by rospogrigio** [comment]
This is driving me crazy. Looks like import_from_yaml does nothing, maybe because config_entries is empty? And why is this happening? When is it being filled?

> With #7 applied, you should debug the import step in `config_flow.py` to see what happens.

Looks like that step is never invoked. I really don't understand some mechanisms here, is it really working for you? If you delete your integrations, are they recreated from YAML?

**Comment by postlund** [comment]
It works as expected for me. Can we begin to clarify what code you are actually running? Is it just master and this PR or anything else as well?

**Comment by postlund** [comment]
And it kinda works like this: if you have this config in YAML:

```yaml
switch:
  - platform: localtuya
     ...
```

Home Assistant will call `setup_platform` in the file `localtuya/switch.py` and pass the config to it. So, that's where I hook in and create a config entry based on the YAML config. So the answer to your question is: it is `import_from_yaml` that triggers the "import" step in `config_flow.py`, which I turn creates the config entry. If a config entry already existed, that will be updated with the new config.

**Comment by rospogrigio** [comment]
I have tried running from current master, and it fails. Then I went backwards, and I saw it began failing at commit 853c1deb...
So I'm applying the code differences piece by piece in order to understand what is breaking everything but it's a hard work.

**Comment by postlund** [comment]
Current master is definitely broken at least. But master with the changes here works for me. Is `setup_platform` called in `switch.py` at all?

**Comment by rospogrigio** [comment]
Found the wrong line. In the import method, I had this:
        `self._set_platform(user_input[CONF_PLATFORM], [])`
While the set_platform method only wants 1 parameter. How am I supposed to publish the fix? Should I create a new PR?

**Comment by rospogrigio** [comment]
I tried to push the fix in this PR, but I don't see the commit here... what am I doing wrong?

**Comment by rospogrigio** [comment]
OK anyways, I fixed it and now master should be stable.
Proceeding with PR #11, at least it is my code so I should handle it easier...

**Comment by postlund** [comment]
Generally you don't push to other people's branches. My suggestion would have been to create a local branch, make your changes, create commit, push branch to GitHub, go to "Pull Requests" page and create a PR (or follow the link from "git push"). That is the general flow.

**Pull request merged**
